CREATE OR REPLACE PROCEDURE GET_M_VIEW_STATS(TABLE_NAME IN VARCHAR2)
IS
    -- 宣言の必要がないため、記載しない
BEGIN
  DBMS_STATS.GATHER_TABLE_STATS(
    OWNNAME          => SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
   ,TABNAME          => TABLE_NAME
   ,ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE
   ,METHOD_OPT       => 'FOR ALL COLUMNS SIZE AUTO'
   ,CASCADE          => TRUE
  );
END GET_M_VIEW_STATS;